version: '3.9'  # Use the appropriate Compose file version

services:
  streamlit:
    build:
      context: ./code
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # Map the host port to the container port
    volumes:
      - ./code:/code  # Mount the current directory to the container
    environment:
      - STREAMLIT_SERVER_PORT=8501  # Ensure Streamlit uses the correct port
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0  # Bind Streamlit to all network interfaces

